version: '3.9'
services:
  postgres-otus-db:
    hostname: postgres-otus-db
    image: bitnami/postgresql:14
    shm_size: 1g
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./01-schema-init.sql:/docker-entrypoint-initdb.d/01-schema-init.sql
      - ./02-data-init.sql:/docker-entrypoint-initdb.d/02-data-init.sql

  redis-otus:
    image: redis:7
    hostname: redis-otus
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  rabbitmq-otus:
    image: rabbitmq:3-management
    hostname: rabbitmq-otus
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3

  # Jaeger
#  jaeger-all-in-one:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686" # Jaeger UI
#      - "14268:14268" # Receive legacy OpenTracing traces, optional
#      - "4317:4317"   # OTLP gRPC receiver
#      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
#      - "14250:14250" # Receive from external otel-collector, optional
#    environment:
#      COLLECTOR_OTLP_ENABLED: true
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55680:55680" # OTLP gRPC receiver alternative port
    depends_on:
      - jaeger-all-in-one